//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<int> FoodID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> CardID { get; set; }
    }
}
