//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int ID { get; set; }
        public string Fullname { get; set; }
        public string PhoneNumber { get; set; }
        public string Note { get; set; }
        public string Address { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public Nullable<int> Point { get; set; }
    }
}
