//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCF
{
    using System;
    using System.Collections.Generic;
    using System.Drawing;
    using System.IO;

    public partial class Food
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Price { get; set; }
        public string Path { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Sector { get; set; }
        public string CategoryName { get; set; }
        public Image Picture
        {
            get
            {
                if (!string.IsNullOrEmpty(Path))
                {
                    if (File.Exists(Path))
                    {
                        return Image.FromFile(Path);
                    }

                }
                return null;
            }
        }
    }
}
